'use strict';

const fs = require('fs');
const path = require('path');
const { test, expect } = require('@playwright/test');
const { buildPdf, buildTruncatedPdf } = require('./helpers/pdf-fixtures');
const { installAppHarness, openApp } = require('./helpers/app');

const ROOT = path.join(__dirname, '..');
const LANGS = fs.readdirSync(path.join(ROOT, 'tools', 'i18n'))
  .filter((f) => f.endsWith('.json'))
  .map((f) => JSON.parse(fs.readFileSync(path.join(ROOT, 'tools', 'i18n', f), 'utf8')));

// The <lang>/index.html pages are generated by tools/build-i18n.mjs. They drifted
// once (CSS order, a missing sister-site link) because index.html was edited
// without regenerating them; this catches that before it ships.
test('localized pages are up to date with index.html', () => {
  const { execFileSync } = require('child_process');
  const before = LANGS.map((d) => fs.readFileSync(path.join(ROOT, d.lang, 'index.html'), 'utf8'));
  execFileSync(process.execPath, [path.join(ROOT, 'tools', 'build-i18n.mjs')], { cwd: ROOT, stdio: 'ignore' });
  const after = LANGS.map((d) => fs.readFileSync(path.join(ROOT, d.lang, 'index.html'), 'utf8'));
  // Put the committed files back, so a failing run leaves the tree as it was.
  LANGS.forEach((d, i) => fs.writeFileSync(path.join(ROOT, d.lang, 'index.html'), before[i]));
  LANGS.forEach((d, i) => {
    expect(after[i] === before[i], `${d.lang}/index.html is stale: run node tools/build-i18n.mjs`).toBe(true);
  });
});

for (const dict of LANGS) {
  test(`/${dict.lang}/ loads the app with every script and no errors`, async ({ page }) => {
    const harness = await installAppHarness(page);
    await openApp(page, `/${dict.lang}/index.html`);

    await expect(page.locator('html')).toHaveAttribute('lang', dict.lang);
    expect(await page.evaluate(() => !!window.I18N_RUNTIME)).toBe(true);
    expect(await page.evaluate(() => typeof window.reportError === 'function')).toBe(true);
    await expect(page.locator('a[href="https://toppdfedittools.com/"]').first()).toBeAttached();
    expect(harness.pageErrors).toEqual([]);
  });
}

test('the "incomplete PDF" message is translated on a localized page', async ({ page }) => {
  const de = LANGS.find((d) => d.lang === 'de');
  await installAppHarness(page);
  await openApp(page, '/de/index.html');
  page.on('dialog', (dialog) => dialog.dismiss());

  await page.setInputFiles('#file1', { name: 'a.pdf', mimeType: 'application/pdf', buffer: buildPdf({ pages: 1 }) });
  await page.setInputFiles('#file2', { name: 'b.pdf', mimeType: 'application/pdf', buffer: buildTruncatedPdf({ pages: 2 }) });
  await page.locator('#simpleMergeBtn').click();

  const expected = de.runtime['This PDF looks incomplete (cut off during download). Re-download it and try again.'];
  await expect(page.locator('#simpleStatus')).toContainText(expected, { timeout: 30_000 });
});
